name: K8Stream
on:
  push:
    paths:
    - '.github/workflows/k8stream.yaml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: make test

    - name: Build
      run: make build_binary

    - name: Get the release tag
      run: echo ::set-env name=VERSION::$(./k8stream --version)

    - uses: AButler/upload-release-assets@v2.0
      with:
        files: 'k8stream'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ env.VERSION }}
