name: K8Stream
on:
  push:
    paths:
      - "**"

jobs:
  test:
    name: K8Stream
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: make test

    - name: Build
      if: github.ref == 'refs/heads/master'
      run: make build_binary

    - name: Get the release tag
      if: github.ref == 'refs/heads/master'
      run: echo "::set-env name=VERSION::$(./k8stream --version > version 2>&1 && cat version)"

    - name: Create Release for x86_64_linux
      if: github.ref == 'refs/heads/master'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: k8stream_x86_64_linux
        draft: false
        prerelease: false

    - name: Upload release asset for x86_64_linux
      if: github.ref == 'refs/heads/master'
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./k8stream
        asset_name: k8stream
        asset_content_type: application/zip
