name: K8Stream
on:
  push:
    paths:
    - '.github/workflows/k8stream.yaml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: make test

    - name: Build
      run: make build_binary

    - name: Get the release tag
      run: echo ::set-env name=VERSION::$(./k8stream --version)

    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'k8stream-{{ env.VERSION }}'
